FOREST = "F"
WATER = "W"
BORDER = "B"
NOTHING = "N"
ENNEMIES = "E"
COLOR_NONE = 0
COLOR_WATER = 1
COLOR_FOREST = 2

COMMAND_LOOK = "LOOK"
COMMAND_MOVE = "MOVE"
COMMAND_STOP = "STOP"
COMMAND_WORK = "WORK"
COMMAND_STATUS = "STATUS"

QUERY_DONE = 2 # query complete, could be executed
QUERY_ERR = 1 # key not authorized
QUERY_NEXT = 0 # query not complete

SIZE = 10

COUNT_PLAYER_TEAMS = 2
COUNT_NPC_TEAMS = 3

SPEED_FACTOR = 1 # 1 normal, 2 faster

DEBUG = False

RATIO_FOREST = 0.2
RATIO_WATER = 0.2
RATIO_WONDER = 0.2

#debug

#RATIO_FOREST = 0.2
SIZE = 3
#RATIO_WATER = 0
SPEED_FACTOR = 40 # 1 normal, 2 faster
DEBUG = True
COUNT_NPC_TEAMS = 10
