# consts 
FOREST = "F"
WATER = "W"
BORDER = "B"
NOTHING = "N"
ENNEMIES = "E"

COMMAND_LOOK = "LOOK"
COMMAND_MOVE = "MOVE"
COMMAND_MOVE_ONCE = "MOVE_ONCE"
COMMAND_STOP = "STOP"
COMMAND_WORK = "WORK"
COMMAND_STATUS = "STATUS"
COMMAND_GET_DIRECTIONS = "GET_DIRECTIONS"

ALL_ALIVE_TEAMS_EXITED = "ALL_ALIVE_TEAMS_EXITED"
ALL_TEAMS_EXITED = "ALL_TEAMS_EXITED"
ALL_TEAMS_DEAD = "ALL_TEAMS_DEAD"
ONE_TEAM_DEAD = "ONE_TEAM_DEAD"

# settings

QUERY_DONE = 2 # query complete, could be executed
QUERY_ERR = 1 # key not authorized
QUERY_NEXT = 0 # query not complete

SIZE = 10

COUNT_PLAYER_TEAMS = 2
COUNT_NPC_TEAMS = 6

SPEED_FACTOR = 1 # 1 normal, 2 faster

DEBUG = False
SUPERMAN = False

RATIO_FOREST = 0.2
RATIO_WATER = 0.2
RATIO_WONDER = 0.2

#debug

RATIO_FOREST = 0
SIZE = 10
RATIO_WATER = 0
SPEED_FACTOR = 20 # 1 normal, 2 faster
DEBUG = True
COUNT_NPC_TEAMS = 20
#SUPERMAN = False
